name: Base PHP Images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    branches:
      - main
      - develop
    paths:
      - php/**
      - .github/workflows/php.yml
      - php-fpm/**
      - scripts/build.sh
jobs:
  legacy-php:
    name: Build Legacy PHP Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        php_version: [ "7.1", "7.2", "7.3" ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images
        env:
          PRE_AUTH: 1
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/centos-php
          VERSION_LIST: ${{ matrix.php_version }}
          VARIANT_LIST: cli cli-loaders fpm fpm-loaders
          PUSH_FLAG: 1
          INDEV_FLAG: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
        run: bash php/scripts/build.sh
        
  php-fpm:
    name: Build Warden PHP-FPM Images ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: [legacy-php]
    strategy:
      matrix:
        php_version: ["7.1", "7.2", "7.3"]
        php_variant: ["fpm-loaders"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images (GitHub)
        env:
          BUILD_GROUP: php-fpm
          PRE_AUTH: 1
          WARDEN_IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}
          PHP_SOURCE_IMAGE: ghcr.io/${{ github.repository_owner }}/centos-php
          PUSH_FLAG: 1
          PHP_VERSION: ${{ matrix.php_version }}
          PHP_VARIANT: ${{ matrix.php_variant }}
          INDEV_FLAG: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
        run: bash scripts/build.sh "${BUILD_GROUP}"

  magento1:
    name: Build Warden PHP-FPM Images ${{ matrix.php_version }} (magento1)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.1", "7.2", "7.3"]
        php_variant: ["fpm-loaders"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images
        env:
          BUILD_GROUP: php-fpm/magento1
          PRE_AUTH: 1
          WARDEN_IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}
          PHP_SOURCE_IMAGE: ghcr.io/${{ github.repository_owner }}/centos-php
          PUSH_FLAG: 1
          PHP_VERSION: ${{ matrix.php_version }}
          PHP_VARIANT: ${{ matrix.php_variant }}
          INDEV_FLAG: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
        run: bash scripts/build.sh "${BUILD_GROUP}"

  magento2:
    name: Build Warden PHP-FPM Images ${{ matrix.php_version }} (magento2)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.1", "7.2", "7.3"]
        php_variant: ["fpm-loaders"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images
        env:
          BUILD_GROUP: php-fpm/magento2
          PRE_AUTH: 1
          WARDEN_IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}
          PHP_SOURCE_IMAGE: ghcr.io/${{ github.repository_owner }}/centos-php
          PUSH_FLAG: 1
          PHP_VERSION: ${{ matrix.php_version }}
          PHP_VARIANT: ${{ matrix.php_variant }}
          INDEV_FLAG: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
        run: bash scripts/build.sh "${BUILD_GROUP}"
